[package]
name = "qasmsim"
version = "0.1.0"
authors = ["Salvador de la Puente González <salva@unoyunodiez.com>"]

[dependencies]
num = "0.2.0"
lalrpop-util = "0.17.2"
regex = "1.3.1"
cached = "0.11.0"

[build-dependencies]
lalrpop = "0.17.2"