[package]
edition = "2018"
name = "qasmsim"
description = "A QASM interpreter and quantum simulator in Rust"
version = "0.1.0"
repository = "git@github.com:delapuente/qasmsim.git"
license = "MIT"
authors = ["Salvador de la Puente González <salva@unoyunodiez.com>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
num = "0.2.1"
lalrpop-util = "0.17.2"
regex = "1.3"
cached = "0.11.0"
float-cmp = "0.6.0"
lazy_static = "1.4.0"
rand = "0.7.3"
wasm-bindgen = "0.2.58"
console_error_panic_hook = "0.1.6"

[build-dependencies]
lalrpop = "0.17.2"
